// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listAiArtifacts: () => typedError<AiArtifact[], string>(__TAURI_INVOKE("list_ai_artifacts")),
	openAiReplayLog: (request: OpenAiReplayLogRequest) => typedError<OpenAiReplayLogResponse, string>(__TAURI_INVOKE("open_ai_replay_log", { request })),
	readAiReplayFrame: (request: ReadAiReplayFrameRequest) => typedError<ReadAiReplayFrameResponse, string>(__TAURI_INVOKE("read_ai_replay_frame", { request })),
	readAiTextFile: (request: ReadAiTextFileRequest) => typedError<ReadAiTextFileResponse, string>(__TAURI_INVOKE("read_ai_text_file", { request })),
	runAiTool: (request: RunAiToolRequest) => typedError<RunAiToolResponse, string>(__TAURI_INVOKE("run_ai_tool", { request })),
	selectAiLogFile: (currentPath: string) => typedError<string | null, string>(__TAURI_INVOKE("select_ai_log_file", { currentPath })),
	getDefaults: () => typedError<Defaults, string>(__TAURI_INVOKE("get_defaults")),
	recordAppContext: (request: RecordAppContextRequest) => typedError<null, string>(__TAURI_INVOKE("record_app_context", { request })),
	recordAppError: (request: RecordAppErrorRequest) => typedError<null, string>(__TAURI_INVOKE("record_app_error", { request })),
	saveRomPaths: (request: SaveRomPathsRequest) => typedError<null, string>(__TAURI_INVOKE("save_rom_paths", { request })),
	saveDiagnosticEventsEnabled: (request: SaveDiagnosticEventsRequest) => typedError<null, string>(__TAURI_INVOKE("save_diagnostic_events_enabled", { request })),
	saveDetailedLogsEnabled: (request: SaveDetailedLogsRequest) => typedError<null, string>(__TAURI_INVOKE("save_detailed_logs_enabled", { request })),
	saveAiPlayLogEnabled: (request: SaveAiPlayLogRequest) => typedError<null, string>(__TAURI_INVOKE("save_ai_play_log_enabled", { request })),
	savePerformanceLogsEnabled: (request: SavePerformanceLogsRequest) => typedError<null, string>(__TAURI_INVOKE("save_performance_logs_enabled", { request })),
	saveNewRoomNotificationsEnabled: (request: SaveNewRoomNotificationsRequest) => typedError<null, string>(__TAURI_INVOKE("save_new_room_notifications_enabled", { request })),
	showNewRoomNotification: (request: ShowNewRoomNotificationRequest) => typedError<boolean, string>(__TAURI_INVOKE("show_new_room_notification", { request })),
	savePlayerName: (request: SavePlayerNameRequest) => typedError<null, string>(__TAURI_INVOKE("save_player_name", { request })),
	selectRomFile: (currentPath: string) => typedError<string | null, string>(__TAURI_INVOKE("select_rom_file", { currentPath })),
	preflightCheck: () => typedError<PreflightResponse, string>(__TAURI_INVOKE("preflight_check")),
	generateRoms: (request: GenerateRomRequest) => typedError<GenerateRomResponse, string>(__TAURI_INVOKE("generate_roms", { request })),
	ensureRoms: (request: GenerateRomRequest) => typedError<GenerateRomResponse, string>(__TAURI_INVOKE("ensure_roms", { request })),
	startMatch: (request: LaunchRequest_Deserialize) => typedError<LaunchResponse, string>(__TAURI_INVOKE("start_match", { request })),
	stopMatch: () => typedError<null, string>(__TAURI_INVOKE("stop_match")),
	sessionStatus: () => typedError<SessionStatus, string>(__TAURI_INVOKE("session_status")),
	upsertMatchHistory: (record: MatchHistoryRecord) => typedError<null, string>(__TAURI_INVOKE("upsert_match_history", { record })),
	deleteMatchHistory: (matchId: string) => typedError<null, string>(__TAURI_INVOKE("delete_match_history", { matchId })),
	queryMatchHistory: (request: MatchHistoryPageRequest) => typedError<MatchHistoryPage, string>(__TAURI_INVOKE("query_match_history", { request })),
	loadMatchHistoryDashboard: (filter: MatchHistoryFilter) => typedError<MatchHistoryDashboard, string>(__TAURI_INVOKE("load_match_history_dashboard", { filter })),
	loadMatchHistoryOpponents: () => typedError<MatchHistoryOpponent[], string>(__TAURI_INVOKE("load_match_history_opponents")),
	openLogDir: (path: string) => typedError<null, string>(__TAURI_INVOKE("open_log_dir", { path })),
	createLogArchive: (logDir: string) => typedError<LogArchiveResponse, string>(__TAURI_INVOKE("create_log_archive", { logDir })),
	cleanupDetailedLogs: () => typedError<CleanupDetailedLogsResponse, string>(__TAURI_INVOKE("cleanup_detailed_logs")),
	uploadLogArchive: (request: UploadLogArchiveRequest) => typedError<UploadLogArchiveResponse, string>(__TAURI_INVOKE("upload_log_archive", { request })),
	openMelonds: () => typedError<number, string>(__TAURI_INVOKE("open_melonds")),
	openMelondsInputConfig: () => typedError<number, string>(__TAURI_INVOKE("open_melonds_input_config")),
	getStartupEnabled: () => typedError<boolean, string>(__TAURI_INVOKE("get_startup_enabled")),
	setStartupEnabled: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_startup_enabled", { enabled })),
};

/* Types */
export type AiArtifact = {
	path: string,
	kind: string,
	bytes: number | null,
	modified_unix_secs: number | null,
};

export type AiReplayFrameRef = {
	index: number,
	frame: number | null,
	byte_offset: number | null,
};

export type BridgeDiagnostics = {
	role: string | null,
	phase: string | null,
	signal_url: string | null,
	session: string | null,
	ice_servers: string[] | null,
	connection_state: string | null,
	gathering_state: string | null,
	ice_state: string | null,
	selected_candidate_pair: SelectedCandidatePair | null,
	stats: BridgeStats | null,
	last_error: string | null,
};

export type BridgeStats = {
	app_to_webrtc_packets: number | null,
	app_to_webrtc_bytes: number | null,
	webrtc_to_app_packets: number | null,
	webrtc_to_app_bytes: number | null,
	dropped_no_local_target: number | null,
};

export type CleanupDetailedLogsResponse = {
	scanned_log_dirs: number,
	skipped_active_log_dirs: number,
	deleted_files: number,
	deleted_dirs: number,
	freed_bytes: number,
};

export type CourseMode = "random" | "select";

export type Defaults = {
	signal_url: string,
	room_code: string,
	host_rom_path: string,
	client_rom_path: string,
	base_rom_path: string,
	player_name: string,
	player_profile_id: string,
	roms_prepared_once: boolean,
	input_config_opened_once: boolean,
	port: number,
	diagnostic_events_enabled: boolean,
	detailed_logs_enabled: boolean,
	ai_play_log_enabled: boolean,
	performance_logs_enabled: boolean,
	new_room_notifications_enabled: boolean,
};

export type FeedbackCategory = "gui" | "connection" | "performance" | "desync" | "crash" | "update" | "other";

export type GameSettings = {
	course_mode: CourseMode,
	course_stages: number[],
	wins: number,
	big_stars: number,
	lives: Lives,
	match_seed: string,
	rng_seeds: string[],
	input_delay_frames: number,
	input_max_frame_lead: number,
	rollback_enabled: boolean,
};

export type GameStateMismatch = {
	instance: number | null,
	frame: number | null,
	local_hash: string | null,
	remote_hash: string | null,
	basic_matches: boolean | null,
	player_global_matches: boolean | null,
	wifi_candidate_matches: boolean | null,
	render_candidate_matches: boolean | null,
	line: string,
};

export type GenerateRomRequest = {
	source_rom: string,
};

export type GenerateRomResponse = {
	host_rom: string,
	client_rom: string,
	generated: boolean,
	rom_identity: RomIdentity,
};

export type LaunchRequest = LaunchRequest_Serialize | LaunchRequest_Deserialize;

export type LaunchRequest_Deserialize = {
	role: Role,
	signal_url: string,
	room_code: string,
	port: number,
	rom_path: string,
	settings: GameSettings,
	player_names?: MatchPlayerNames | null,
	diagnostic_events_enabled?: boolean,
	detailed_logs_enabled?: boolean,
	ai_play_log_enabled?: boolean,
	performance_logs_enabled: boolean,
	rom_identity?: RomIdentity | null,
};

export type LaunchRequest_Serialize = {
	role: Role,
	signal_url: string,
	room_code: string,
	port: number,
	rom_path: string,
	settings: GameSettings,
	player_names?: MatchPlayerNames | null,
	diagnostic_events_enabled: boolean,
	detailed_logs_enabled: boolean,
	ai_play_log_enabled: boolean,
	performance_logs_enabled: boolean,
	rom_identity?: RomIdentity | null,
};

export type LaunchResponse = {
	log_dir: string,
	melon_pid: number,
	bridge_pid: number,
};

export type Lives = "3" | "5" | "endless";

export type LogArchiveResponse = {
	archive_path: string,
	size: number,
	included_files: string[],
};

export type MatchHistoryCursor = {
	startedAt: string,
	id: string,
};

export type MatchHistoryDashboard = {
	summary: MatchHistorySummary,
	trend: MatchHistoryTrendPoint[],
	stages: MatchHistoryStageStatistics[],
};

export type MatchHistoryFilter = {
	recentMatches: number | null,
	sinceStartedAt: string | null,
	opponentPlayerId: string | null,
	stage: number | null,
	outcome: MatchHistoryOutcome | null,
};

export type MatchHistoryOpponent = {
	playerId: string,
	latestName: string,
	matches: number,
	lastPlayedAt: string,
};

export type MatchHistoryOutcome = "completed" | "win" | "loss" | "stopped";

export type MatchHistoryPage = {
	matches: MatchHistoryRecord[],
	nextCursor: MatchHistoryCursor | null,
	total: number,
};

export type MatchHistoryPageRequest = {
	filter: MatchHistoryFilter,
	cursor: MatchHistoryCursor | null,
	limit: number,
};

export type MatchHistoryRecord = {
	id: string,
	logDir: string,
	playerIds: MatchPlayerIds,
	playerNames: MatchPlayerNames,
	role: Role,
	roomCode: string,
	settings: GameSettings,
	stages: MvlStageResult[],
	startedAt: string,
	status: MatchHistoryStatus,
};

export type MatchHistoryStageStatistics = {
	stage: number,
	wins: number,
	losses: number,
};

export type MatchHistoryStatus = "running" | "completed" | "stopped";

export type MatchHistoryStreakKind = "win" | "loss";

export type MatchHistorySummary = {
	wins: number,
	losses: number,
	stopped: number,
	gameWins: number,
	gameLosses: number,
	streak: number,
	streakKind: MatchHistoryStreakKind | null,
};

export type MatchHistoryTrendPoint = {
	matchId: string,
	startedAt: string,
	opponentName: string,
	won: boolean,
	rollingWinRate: number | null,
};

export type MatchPlayerIds = {
	mario: string,
	luigi: string,
};

export type MatchPlayerNames = {
	mario: string,
	luigi: string,
};

export type MvlPlayerResult = {
	stars: number,
	displayed_stars: number,
	collected_stars: number,
	lives: number,
	deaths: number,
	dead: boolean,
};

export type MvlStageResult = {
	game_index: number,
	stage: number | null,
	frame: number,
	winner: number | null,
	mario: MvlPlayerResult,
	luigi: MvlPlayerResult,
	mario_match_wins: number,
	luigi_match_wins: number,
	target_wins: number,
	resolved: boolean,
	line: string,
};

export type OpenAiReplayLogRequest = {
	path: string,
};

export type OpenAiReplayLogResponse = {
	source_path: string,
	data_path: string,
	compressed: boolean,
	original_bytes: number | null,
	data_bytes: number | null,
	frames: AiReplayFrameRef[],
};

export type PreflightResponse = {
	melonds_path: string,
	bridge_path: string,
	input_script: string,
	symbols_file: string,
	bridge_smoke: string,
};

export type ReadAiReplayFrameRequest = {
	data_path: string,
	byte_offset: number | null,
	previous_byte_offset: number | null,
};

export type ReadAiReplayFrameResponse = {
	frame_json: string,
	previous_frame_json: string | null,
};

export type ReadAiTextFileRequest = {
	path: string,
};

export type ReadAiTextFileResponse = {
	path: string,
	text: string,
	sampled: boolean,
	original_bytes: number | null,
	sampled_lines: number,
};

export type RecordAppContextRequest = {
	user_agent: string,
	language: string,
	hardware_concurrency: number,
	device_memory_gib: number | null,
	screen_width: number,
	screen_height: number,
	device_pixel_ratio: number | null,
	gpu_renderer: string | null,
};

export type RecordAppErrorRequest = {
	source: string,
	operation: string,
	message: string,
	stack: string | null,
};

export type Role = "host" | "client";

export type RomIdentity = {
	rom_pair_id: string,
	generator_id: string,
	host_rom_sha256: string,
	client_rom_sha256: string,
	bridge_sha256?: string,
};

export type RunAiToolRequest = {
	task: string,
	input_path: string | null,
	output_path: string | null,
	session_path: string | null,
	dataset_path: string | null,
	model_path: string | null,
	runtime_model_path: string | null,
	log_dir: string | null,
	scenario: string | null,
	policy: string | null,
	seed: string | null,
	label_source: string | null,
	player: number | null,
	frame: number | null,
	frames: number | null,
	epochs: number | null,
	threshold: number | null,
	max_objects: number | null,
	dry_run: boolean | null,
	split_by_recording: boolean | null,
	allow_jit: boolean | null,
	dual_window: boolean | null,
	no_packet_capture: boolean | null,
	scan_frames: boolean | null,
};

export type RunAiToolResponse = {
	cwd: string,
	command_line: string,
	exit_code: number | null,
	stdout: string,
	stderr: string,
	output_path: string | null,
};

export type SaveAiPlayLogRequest = {
	enabled: boolean,
};

export type SaveDetailedLogsRequest = {
	enabled: boolean,
};

export type SaveDiagnosticEventsRequest = {
	enabled: boolean,
};

export type SaveNewRoomNotificationsRequest = {
	enabled: boolean,
};

export type SavePerformanceLogsRequest = {
	enabled: boolean,
};

export type SavePlayerNameRequest = {
	player_name: string,
};

export type SaveRomPathsRequest = {
	base_rom_path: string,
};

export type SelectedCandidatePair = {
	route: string | null,
	local_type: string | null,
	remote_type: string | null,
	local: string | null,
	remote: string | null,
	local_address: string | null,
	remote_address: string | null,
};

export type SessionStatus = {
	active: boolean,
	log_dir: string | null,
	melon: string | null,
	bridge: string | null,
	webrtc: BridgeDiagnostics | null,
	diagnostics_error: string | null,
	game_state_mismatch: GameStateMismatch | null,
	mvl_results: MvlStageResult[],
};

export type ShowNewRoomNotificationRequest = {
	title: string,
	body: string,
};

export type UploadLogArchiveRequest = {
	log_dir: string,
	upload_url: string,
	category: FeedbackCategory,
	description: string,
	include_performance: boolean,
};

export type UploadLogArchiveResponse = {
	report_id: string,
	size: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}
