// Generated by Kiso CLI. Edit individual recipe files; add components with the CLI.
import { alert } from './alert'
import { badge } from './badge'
import { button } from './button'
import { card } from './card'
import { dialog } from './dialog'
import { field } from './field'
import { input } from './input'
import { numberField } from './number-field'
import { progress } from './progress'
import { spinner } from './spinner'
import { switchRecipe } from './switch'

// prettier-ignore
export const recipes = { badge, button, input, spinner }
// prettier-ignore
export const slotRecipes = { alert, card, dialog, field, numberField, progress, switchRecipe }
