#include "NsmbInputTimeline.h"

#include <algorithm>
#include <cctype>
#include <cstdlib>
#include <fstream>
#include <sstream>

namespace NsmbMvlNetplay::InputTimeline
{

namespace
{

std::string Trim(std::string value)
{
    const auto first = value.find_first_not_of(" \t\r\n");
    if (first == std::string::npos)
        return {};
    const auto last = value.find_last_not_of(" \t\r\n");
    return value.substr(first, last - first + 1);
}

std::string Upper(std::string value)
{
    for (char& ch : value)
        ch = static_cast<char>(std::toupper(static_cast<unsigned char>(ch)));
    return value;
}

bool ParseU32(const std::string& text, melonDS::u32& out)
{
    char* end = nullptr;
    const unsigned long value = std::strtoul(text.c_str(), &end, 0);
    if (!end || *end != '\0')
        return false;
    out = static_cast<melonDS::u32>(value);
    return true;
}

int ButtonBit(const std::string& name)
{
    const std::string key = Upper(name);
    if (key == "A") return 0;
    if (key == "B") return 1;
    if (key == "SELECT") return 2;
    if (key == "START") return 3;
    if (key == "RIGHT") return 4;
    if (key == "LEFT") return 5;
    if (key == "UP") return 6;
    if (key == "DOWN") return 7;
    if (key == "R") return 8;
    if (key == "L") return 9;
    if (key == "X") return 10;
    if (key == "Y") return 11;
    return -1;
}

bool InputsEqual(const InputState& left, const InputState& right)
{
    return left.KeyMask == right.KeyMask
        && left.Touching == right.Touching
        && left.TouchX == right.TouchX
        && left.TouchY == right.TouchY;
}

std::string InputSpecForScript(const InputState& input)
{
    static constexpr const char* kButtonNames[12] {
        "A",
        "B",
        "SELECT",
        "START",
        "RIGHT",
        "LEFT",
        "UP",
        "DOWN",
        "R",
        "L",
        "X",
        "Y",
    };

    std::string spec;
    for (int bit = 0; bit < 12; bit++)
    {
        if ((input.KeyMask & (1u << bit)) != 0)
            continue;
        if (!spec.empty())
            spec += "+";
        spec += kButtonNames[bit];
    }
    if (spec.empty())
        spec = "NONE";
    if (input.Touching)
    {
        spec += " ";
        spec += std::to_string(input.TouchX);
        spec += ",";
        spec += std::to_string(input.TouchY);
    }
    return spec;
}

}

Recorder::~Recorder()
{
    Close();
}

bool Recorder::Open(
    const std::string& path,
    melonDS::u32 startFrame,
    melonDS::u32 endFrame,
    int instanceID)
{
    Close();
    std::lock_guard<std::mutex> lock(Mutex_);
    Output_.open(path, std::ios::out | std::ios::trunc);
    if (!Output_)
        return false;

    StartFrame_ = startFrame;
    EndFrame_ = endFrame;
    InstanceID_ = instanceID;
    HasSpan_ = false;
    PendingSpans_ = 0;
    Output_ << "# NSMB input recording generated by melonDS NSML PoC\n";
    Output_ << "# startFrame=" << StartFrame_
        << " endFrame=" << EndFrame_
        << " instance=" << InstanceID_ << "\n";
    Output_.flush();
    Enabled_.store(true, std::memory_order_release);
    return true;
}

bool Recorder::IsOpen() const
{
    return Enabled_.load(std::memory_order_acquire);
}

void Recorder::Record(int instanceID, melonDS::u32 frame, const InputState& input)
{
    if (!Enabled_.load(std::memory_order_acquire))
        return;
    std::lock_guard<std::mutex> lock(Mutex_);
    if (!Output_)
        return;
    if (InstanceID_ >= 0 && InstanceID_ != instanceID)
        return;
    if (frame < StartFrame_ || (EndFrame_ != 0 && frame > EndFrame_))
        return;

    InputState recordInput = input;
    recordInput.KeyMask &= 0xFFF;
    if (!HasSpan_)
    {
        SpanStart_ = frame;
        SpanEnd_ = frame;
        SpanInput_ = recordInput;
        HasSpan_ = true;
        return;
    }

    if (SpanEnd_ + 1 == frame && InputsEqual(SpanInput_, recordInput))
    {
        SpanEnd_ = frame;
        return;
    }
    if (frame <= SpanEnd_)
    {
        if (!InputsEqual(SpanInput_, recordInput)
            && SpanStart_ == frame
            && SpanEnd_ == frame)
        {
            SpanInput_ = recordInput;
        }
        return;
    }

    FlushSpanLocked();
    SpanStart_ = frame;
    SpanEnd_ = frame;
    SpanInput_ = recordInput;
    HasSpan_ = true;
}

void Recorder::Close()
{
    Enabled_.store(false, std::memory_order_release);
    std::lock_guard<std::mutex> lock(Mutex_);
    FlushSpanLocked();
    if (Output_.is_open())
        Output_.close();
}

void Recorder::FlushSpanLocked()
{
    if (!Output_ || !HasSpan_)
        return;

    Output_ << SpanStart_ << "-" << SpanEnd_ << " "
        << InputSpecForScript(SpanInput_) << "\n";
    HasSpan_ = false;
    PendingSpans_++;
    if (PendingSpans_ >= 64)
    {
        Output_.flush();
        PendingSpans_ = 0;
    }
}

ConfirmedInputResult PredictionRuntime::Confirm(
    melonDS::u32 frame,
    const InputState& input,
    std::optional<melonDS::u32> localFrame)
{
    ConfirmedInputResult result;
    const auto predicted = Predictions_.find(frame);
    if (predicted != Predictions_.end() && !InputsEqual(predicted->second, input))
    {
        result.Mismatch = true;
        result.PredictedInput = predicted->second;
        result.FrameAlreadySimulated = !localFrame || frame < *localFrame;
        MismatchCount_++;

        if (result.FrameAlreadySimulated)
        {
            const melonDS::u32 observedFrame = localFrame.value_or(frame);
            if (!PendingRollbackFrame_ || frame < *PendingRollbackFrame_)
            {
                PendingRollbackFrame_ = frame;
                PendingRollbackObservedFrame_ = observedFrame;
            }
            else if (!PendingRollbackObservedFrame_)
            {
                PendingRollbackObservedFrame_ = observedFrame;
            }
        }
        Predictions_.erase(Predictions_.lower_bound(frame), Predictions_.end());
        PredictionProbeConfirmations_.erase(
            PredictionProbeConfirmations_.lower_bound(frame),
            PredictionProbeConfirmations_.end());
    }

    PredictionProbeConfirmations_.erase(frame);

    LastConfirmedInput_ = input;
    return result;
}

PredictedInput PredictionRuntime::Resolve(
    melonDS::u32 frame,
    const InputMap& confirmedInputs,
    const InputState& neutralInput,
    const PredictionProbe& probe)
{
    const bool belowProbeLimit = probe.Limit < 0
        || PredictionProbeCount_ < static_cast<melonDS::u32>(probe.Limit);
    const bool insideProbeRange = frame >= probe.StartFrame
        && (!probe.EndFrame || frame <= *probe.EndFrame);
    const bool applyProbe = probe.Modulo > 0
        && belowProbeLimit
        && insideProbeRange
        && (frame % static_cast<melonDS::u32>(probe.Modulo))
            == static_cast<melonDS::u32>(probe.Offset);

    const auto confirmed = confirmedInputs.find(frame);
    if (confirmed != confirmedInputs.end())
    {
        if (applyProbe && probe.ConfirmAfterOneFrame)
        {
            InputState input = confirmed->second;
            PredictionProbeConfirmations_[frame] = input;
            input.KeyMask ^= probe.KeyMask & 0xFFFu;
            Predictions_[frame] = input;
            PredictionProbeCount_++;
            PredictionCount_++;
            return { input, true };
        }
        return { confirmed->second, false };
    }

    const auto existing = Predictions_.find(frame);
    if (existing != Predictions_.end())
        return { existing->second, true };

    InputState input = neutralInput;
    const auto previous = frame > 0
        ? Predictions_.find(frame - 1)
        : Predictions_.end();
    if (previous != Predictions_.end())
        input = previous->second;
    else if (LastConfirmedInput_)
        input = *LastConfirmedInput_;

    if (applyProbe)
    {
        if (probe.ConfirmAfterOneFrame)
            PredictionProbeConfirmations_.emplace(frame, input);
        input.KeyMask ^= probe.KeyMask & 0xFFFu;
        PredictionProbeCount_++;
    }

    Predictions_.emplace(frame, input);
    PredictionCount_++;
    return { input, true };
}

void PredictionRuntime::Prune(
    melonDS::u32 currentFrame,
    melonDS::u32 window,
    const InputMap& confirmedInputs)
{
    const melonDS::u32 keepFrom = currentFrame > window ? currentFrame - window : 0;
    for (auto prediction = Predictions_.begin(); prediction != Predictions_.end();)
    {
        if (prediction->first < keepFrom
            && confirmedInputs.find(prediction->first) != confirmedInputs.end())
        {
            prediction = Predictions_.erase(prediction);
        }
        else
        {
            ++prediction;
        }
    }
}

void PredictionRuntime::ClearPredictions()
{
    Predictions_.clear();
    PredictionProbeConfirmations_.clear();
}

std::optional<InputState> PredictionRuntime::TakePredictionProbeConfirmation(
    melonDS::u32 frame)
{
    const auto confirmation = PredictionProbeConfirmations_.find(frame);
    if (confirmation == PredictionProbeConfirmations_.end())
        return std::nullopt;

    const InputState input = confirmation->second;
    PredictionProbeConfirmations_.erase(confirmation);
    return input;
}

const PredictionRuntime::InputMap& PredictionRuntime::Predictions() const
{
    return Predictions_;
}

std::optional<melonDS::u32> PredictionRuntime::PendingRollbackFrame() const
{
    return PendingRollbackFrame_;
}

std::optional<melonDS::u32> PredictionRuntime::PendingRollbackObservedFrame() const
{
    return PendingRollbackObservedFrame_;
}

void PredictionRuntime::ClearPendingRollbackFrame()
{
    PendingRollbackFrame_.reset();
}

void PredictionRuntime::ClearPendingRollback()
{
    PendingRollbackFrame_.reset();
    PendingRollbackObservedFrame_.reset();
}

melonDS::u32 PredictionRuntime::PredictionCount() const
{
    return PredictionCount_;
}

melonDS::u32 PredictionRuntime::PredictionProbeCount() const
{
    return PredictionProbeCount_;
}

melonDS::u32 PredictionRuntime::MismatchCount() const
{
    return MismatchCount_;
}

void Runtime::ResetForRestart(melonDS::u32 noFrameLimit)
{
    LocalInputs.clear();
    RemoteInputs.clear();
    RollbackInputs.ClearPredictions();
    LastReceivedInputFrame = noFrameLimit;
    LastSentInputFrame = noFrameLimit;
    LastTracedSentInputFrame = noFrameLimit;
    LastTracedReceivedInputFrame = noFrameLimit;
    LastInputHealthSummaryFrame = noFrameLimit;
    LastInputHealthRemoteWaitFrame = noFrameLimit;
    LastInputHealthThrottleFrame = noFrameLimit;
    LastInputHealthThrottleResolvedFrame = noFrameLimit;
    LastInputHealthReceiveGapFrame = noFrameLimit;
    LastInputHealthSendGapFrame = noFrameLimit;
    LastInputFrameThrottleTraceFrame = noFrameLimit;
    LastInputFrameLeadResendAt = {};
    InputFrameLeadResendCount = 0;
}

RemoteInputStoreResult Runtime::StoreRemote(
    melonDS::u32 frame,
    const InputState& input,
    std::optional<melonDS::u32> localFrame,
    bool confirmPrediction,
    melonDS::u32 noFrameLimit)
{
    RemoteInputStoreResult result;
    result.PreviousLastReceived = LastReceivedInputFrame;
    if (confirmPrediction)
        result.Confirmation = RollbackInputs.Confirm(frame, input, localFrame);
    RemoteInputs[frame] = input;
    if (LastReceivedInputFrame == noFrameLimit || LastReceivedInputFrame < frame)
        LastReceivedInputFrame = frame;
    return result;
}

void Runtime::PruneHistory(melonDS::u32 keepFromFrame)
{
    LocalInputs.erase(LocalInputs.begin(), LocalInputs.lower_bound(keepFromFrame));
    RemoteInputs.erase(RemoteInputs.begin(), RemoteInputs.lower_bound(keepFromFrame));
}

void Runtime::PrimeEpoch(
    melonDS::u32 startFrame,
    melonDS::u32 delay,
    const InputState& neutralInput,
    melonDS::u32 noFrameLimit)
{
    PruneHistory(startFrame);
    const melonDS::u32 firstInputFrame = startFrame + delay;
    for (melonDS::u32 frame = startFrame; frame < firstInputFrame; frame++)
    {
        LocalInputs.emplace(frame, neutralInput);
        RemoteInputs.emplace(frame, neutralInput);
    }
    if (delay == 0)
        return;

    const melonDS::u32 primedThrough = firstInputFrame - 1;
    if (LastReceivedInputFrame == noFrameLimit || LastReceivedInputFrame < primedThrough)
        LastReceivedInputFrame = primedThrough;
}

int Runtime::Lead(melonDS::u32 sendFrame, melonDS::u32 noFrameLimit) const
{
    if (LastReceivedInputFrame == noFrameLimit)
        return 0;
    return static_cast<int>(sendFrame) - static_cast<int>(LastReceivedInputFrame);
}

void Runtime::RecordRemoteInputWait(unsigned long long elapsedUs, unsigned long long loops)
{
    RemoteInputWaitCount++;
    RemoteInputWaitLoops += loops;
    RemoteInputWaitUs += elapsedUs;
    RemoteInputWaitMaxUs = std::max(RemoteInputWaitMaxUs, elapsedUs);
}

void Runtime::RecordFrameLeadThrottle(unsigned long long elapsedUs, unsigned long long loops)
{
    FrameLeadThrottleCount++;
    FrameLeadThrottleLoops += loops;
    FrameLeadThrottleUs += elapsedUs;
    FrameLeadThrottleMaxUs = std::max(FrameLeadThrottleMaxUs, elapsedUs);
}

std::optional<ReplayFrameInputs> ResolveReplayFrameInputs(
    Runtime& runtime,
    melonDS::u32 frame,
    int localPlayer,
    const InputState& neutralInput,
    const PredictionProbe& probe)
{
    if (localPlayer < 0 || localPlayer > 1)
        return std::nullopt;

    ReplayFrameInputs result;
    const auto local = runtime.LocalInputs.find(frame);
    if (local != runtime.LocalInputs.end())
        result.Local = local->second;
    else
        result.Local = neutralInput;

    const PredictedInput remote = runtime.RollbackInputs.Resolve(
        frame, runtime.RemoteInputs, neutralInput, probe);
    result.Remote = remote.Input;
    result.RemotePredicted = remote.Predicted;
    result.Players[localPlayer] = result.Local;
    result.Players[1 - localPlayer] = result.Remote;
    return result;
}

bool ParseInputSpec(const std::string& spec, InputState& input)
{
    input = {};

    if (spec.empty() || Upper(spec) == "NONE" || Upper(spec) == "NEUTRAL")
        return true;

    if (spec.rfind("mask=", 0) == 0 || spec.rfind("MASK=", 0) == 0)
    {
        melonDS::u32 mask = 0;
        if (!ParseU32(spec.substr(5), mask))
            return false;
        input.KeyMask = mask & 0xFFF;
        return true;
    }

    std::stringstream stream(spec);
    std::string button;
    while (std::getline(stream, button, '+'))
    {
        const int bit = ButtonBit(Trim(button));
        if (bit < 0)
            return false;
        input.KeyMask &= ~(1u << bit);
    }
    return true;
}

bool ParseInputScript(std::istream& input, std::vector<InputSpan>& spans, ParseError& error)
{
    spans.clear();
    error = {};

    std::string line;
    int lineNo = 0;
    while (std::getline(input, line))
    {
        lineNo++;
        const auto comment = line.find('#');
        if (comment != std::string::npos)
            line.resize(comment);
        line = Trim(line);
        if (line.empty())
            continue;

        std::stringstream stream(line);
        std::string target;
        std::string range;
        std::string buttons;
        std::string touch;
        stream >> target >> range >> buttons >> touch;

        InputSpan span;
        if (target.find('-') != std::string::npos)
        {
            touch = buttons;
            buttons = range;
            range = target;
        }
        else
        {
            const std::string upperTarget = Upper(target);
            if (upperTarget != "ALL")
            {
                constexpr const char* prefix = "INST";
                melonDS::u32 targetInstance = 0;
                if (upperTarget.rfind(prefix, 0) != 0 ||
                    !ParseU32(upperTarget.substr(4), targetInstance) ||
                    targetInstance >= 16)
                {
                    error = { ParseErrorKind::Target, lineNo };
                    return false;
                }
                span.Instance = static_cast<int>(targetInstance);
            }
        }

        const auto dash = range.find('-');
        if (dash == std::string::npos)
        {
            error = { ParseErrorKind::Range, lineNo };
            return false;
        }
        if (!ParseU32(range.substr(0, dash), span.Start) ||
            !ParseU32(range.substr(dash + 1), span.End) ||
            span.End < span.Start ||
            !ParseInputSpec(buttons, span.Input))
        {
            error = { ParseErrorKind::Input, lineNo };
            return false;
        }

        if (!touch.empty())
        {
            const auto comma = touch.find(',');
            melonDS::u32 x = 0;
            melonDS::u32 y = 0;
            if (comma == std::string::npos ||
                !ParseU32(touch.substr(0, comma), x) ||
                !ParseU32(touch.substr(comma + 1), y))
            {
                error = { ParseErrorKind::Touch, lineNo };
                return false;
            }
            span.Input.Touching = true;
            span.Input.TouchX = static_cast<melonDS::u16>(std::min<melonDS::u32>(x, 255));
            span.Input.TouchY = static_cast<melonDS::u16>(std::min<melonDS::u32>(y, 191));
        }
        spans.push_back(span);
    }
    return true;
}

bool LoadInputScriptFile(
    const std::string& path,
    std::vector<InputSpan>& spans,
    ParseError& error)
{
    std::ifstream file(path);
    if (!file)
    {
        spans.clear();
        error = { ParseErrorKind::Open, 0 };
        return false;
    }
    return ParseInputScript(file, spans, error);
}

InputState Apply(
    const std::vector<InputSpan>& spans,
    int instanceID,
    melonDS::u32 frame,
    const InputState& fallback)
{
    for (const InputSpan& span : spans)
    {
        if ((span.Instance < 0 || span.Instance == instanceID) &&
            frame >= span.Start && frame <= span.End)
        {
            return span.Input;
        }
    }
    return fallback;
}

}
