// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getDefaults: () => typedError<Defaults, string>(__TAURI_INVOKE("get_defaults")),
	saveRomPaths: (request: SaveRomPathsRequest) => typedError<null, string>(__TAURI_INVOKE("save_rom_paths", { request })),
	selectRomFile: (currentPath: string) => typedError<string | null, string>(__TAURI_INVOKE("select_rom_file", { currentPath })),
	preflightCheck: () => typedError<PreflightResponse, string>(__TAURI_INVOKE("preflight_check")),
	generateRoms: (request: GenerateRomRequest) => typedError<GenerateRomResponse, string>(__TAURI_INVOKE("generate_roms", { request })),
	ensureRoms: (request: GenerateRomRequest) => typedError<GenerateRomResponse, string>(__TAURI_INVOKE("ensure_roms", { request })),
	startMatch: (request: LaunchRequest) => typedError<LaunchResponse, string>(__TAURI_INVOKE("start_match", { request })),
	stopMatch: () => typedError<null, string>(__TAURI_INVOKE("stop_match")),
	sessionStatus: () => typedError<SessionStatus, string>(__TAURI_INVOKE("session_status")),
	openLogDir: (path: string) => typedError<null, string>(__TAURI_INVOKE("open_log_dir", { path })),
	openMelonds: () => typedError<number, string>(__TAURI_INVOKE("open_melonds")),
	openMelondsInputConfig: () => typedError<number, string>(__TAURI_INVOKE("open_melonds_input_config")),
};

/* Types */
export type BridgeDiagnostics = {
	role: string | null,
	phase: string | null,
	signal_url: string | null,
	session: string | null,
	ice_servers: string[] | null,
	connection_state: string | null,
	gathering_state: string | null,
	ice_state: string | null,
	selected_candidate_pair: SelectedCandidatePair | null,
	stats: BridgeStats | null,
	last_error: string | null,
};

export type BridgeStats = {
	app_to_webrtc_packets: number | null,
	app_to_webrtc_bytes: number | null,
	webrtc_to_app_packets: number | null,
	webrtc_to_app_bytes: number | null,
	dropped_no_local_target: number | null,
};

export type CourseMode = "random" | "select";

export type Defaults = {
	signal_url: string,
	room_code: string,
	host_rom_path: string,
	client_rom_path: string,
	base_rom_path: string,
	port: number,
};

export type GameSettings = {
	course_mode: CourseMode,
	wins: number,
	big_stars: number,
	lives: Lives,
	match_seed: string,
};

export type GenerateRomRequest = {
	source_rom: string,
	host_rom: string,
	client_rom: string,
	stage: number,
	settings: GameSettings,
};

export type GenerateRomResponse = {
	host_rom: string,
	client_rom: string,
	generated: boolean,
};

export type LaunchRequest = {
	role: Role,
	signal_url: string,
	room_code: string,
	port: number,
	rom_path: string,
	settings: GameSettings,
};

export type LaunchResponse = {
	log_dir: string,
	melon_pid: number,
	bridge_pid: number,
};

export type Lives = "3" | "5" | "endless";

export type PreflightResponse = {
	melonds_path: string,
	bridge_path: string,
	input_script: string,
	symbols_file: string,
	bridge_smoke: string,
};

export type Role = "host" | "client";

export type SaveRomPathsRequest = {
	host_rom_path: string,
	client_rom_path: string,
	base_rom_path: string,
};

export type SelectedCandidatePair = {
	route: string | null,
	local_type: string | null,
	remote_type: string | null,
	local: string | null,
	remote: string | null,
	local_address: string | null,
	remote_address: string | null,
};

export type SessionStatus = {
	active: boolean,
	log_dir: string | null,
	melon: string | null,
	bridge: string | null,
	webrtc: BridgeDiagnostics | null,
	diagnostics_error: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

