// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listAiArtifacts: () => typedError<AiArtifact[], string>(__TAURI_INVOKE("list_ai_artifacts")),
	readAiTextFile: (request: ReadAiTextFileRequest) => typedError<ReadAiTextFileResponse, string>(__TAURI_INVOKE("read_ai_text_file", { request })),
	runAiTool: (request: RunAiToolRequest) => typedError<RunAiToolResponse, string>(__TAURI_INVOKE("run_ai_tool", { request })),
	selectAiLogFile: (currentPath: string) => typedError<string | null, string>(__TAURI_INVOKE("select_ai_log_file", { currentPath })),
	getDefaults: () => typedError<Defaults, string>(__TAURI_INVOKE("get_defaults")),
	saveRomPaths: (request: SaveRomPathsRequest) => typedError<null, string>(__TAURI_INVOKE("save_rom_paths", { request })),
	selectRomFile: (currentPath: string) => typedError<string | null, string>(__TAURI_INVOKE("select_rom_file", { currentPath })),
	preflightCheck: () => typedError<PreflightResponse, string>(__TAURI_INVOKE("preflight_check")),
	generateRoms: (request: GenerateRomRequest) => typedError<GenerateRomResponse, string>(__TAURI_INVOKE("generate_roms", { request })),
	ensureRoms: (request: GenerateRomRequest) => typedError<GenerateRomResponse, string>(__TAURI_INVOKE("ensure_roms", { request })),
	startMatch: (request: LaunchRequest) => typedError<LaunchResponse, string>(__TAURI_INVOKE("start_match", { request })),
	stopMatch: () => typedError<null, string>(__TAURI_INVOKE("stop_match")),
	sessionStatus: () => typedError<SessionStatus, string>(__TAURI_INVOKE("session_status")),
	openLogDir: (path: string) => typedError<null, string>(__TAURI_INVOKE("open_log_dir", { path })),
	openMelonds: () => typedError<number, string>(__TAURI_INVOKE("open_melonds")),
	openMelondsInputConfig: () => typedError<number, string>(__TAURI_INVOKE("open_melonds_input_config")),
};

/* Types */
export type AiArtifact = {
	path: string,
	kind: string,
	bytes: number | null,
	modified_unix_secs: number | null,
};

export type BridgeDiagnostics = {
	role: string | null,
	phase: string | null,
	signal_url: string | null,
	session: string | null,
	ice_servers: string[] | null,
	connection_state: string | null,
	gathering_state: string | null,
	ice_state: string | null,
	selected_candidate_pair: SelectedCandidatePair | null,
	stats: BridgeStats | null,
	last_error: string | null,
};

export type BridgeStats = {
	app_to_webrtc_packets: number | null,
	app_to_webrtc_bytes: number | null,
	webrtc_to_app_packets: number | null,
	webrtc_to_app_bytes: number | null,
	dropped_no_local_target: number | null,
};

export type CourseMode = "random" | "select";

export type Defaults = {
	signal_url: string,
	room_code: string,
	host_rom_path: string,
	client_rom_path: string,
	base_rom_path: string,
	roms_prepared_once: boolean,
	input_config_opened_once: boolean,
	port: number,
};

export type GameSettings = {
	course_mode: CourseMode,
	course_stages: number[],
	wins: number,
	big_stars: number,
	lives: Lives,
	match_seed: string,
	rng_seeds: string[],
	input_delay_frames: number,
	input_max_frame_lead: number,
	rollback_enabled: boolean,
};

export type GenerateRomRequest = {
	source_rom: string,
	stage: number,
	settings: GameSettings,
};

export type GenerateRomResponse = {
	host_rom: string,
	client_rom: string,
	generated: boolean,
};

export type LaunchRequest = {
	role: Role,
	signal_url: string,
	room_code: string,
	port: number,
	rom_path: string,
	settings: GameSettings,
};

export type LaunchResponse = {
	log_dir: string,
	melon_pid: number,
	bridge_pid: number,
};

export type Lives = "3" | "5" | "endless";

export type PreflightResponse = {
	melonds_path: string,
	bridge_path: string,
	input_script: string,
	symbols_file: string,
	bridge_smoke: string,
};

export type ReadAiTextFileRequest = {
	path: string,
};

export type ReadAiTextFileResponse = {
	path: string,
	text: string,
	sampled: boolean,
	original_bytes: number | null,
	sampled_lines: number,
};

export type Role = "host" | "client";

export type RunAiToolRequest = {
	task: string,
	input_path: string | null,
	output_path: string | null,
	session_path: string | null,
	dataset_path: string | null,
	model_path: string | null,
	runtime_model_path: string | null,
	log_dir: string | null,
	scenario: string | null,
	policy: string | null,
	seed: string | null,
	label_source: string | null,
	player: number | null,
	frame: number | null,
	frames: number | null,
	epochs: number | null,
	threshold: number | null,
	max_objects: number | null,
	dry_run: boolean | null,
	split_by_recording: boolean | null,
	allow_jit: boolean | null,
	dual_window: boolean | null,
	no_packet_capture: boolean | null,
	scan_frames: boolean | null,
};

export type RunAiToolResponse = {
	cwd: string,
	command_line: string,
	exit_code: number | null,
	stdout: string,
	stderr: string,
	output_path: string | null,
};

export type SaveRomPathsRequest = {
	base_rom_path: string,
};

export type SelectedCandidatePair = {
	route: string | null,
	local_type: string | null,
	remote_type: string | null,
	local: string | null,
	remote: string | null,
	local_address: string | null,
	remote_address: string | null,
};

export type SessionStatus = {
	active: boolean,
	log_dir: string | null,
	melon: string | null,
	bridge: string | null,
	webrtc: BridgeDiagnostics | null,
	diagnostics_error: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

