// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getDefaults: () => typedError<Defaults, string>(__TAURI_INVOKE("get_defaults")),
	saveRomPaths: (request: SaveRomPathsRequest) => typedError<null, string>(__TAURI_INVOKE("save_rom_paths", { request })),
	saveDiagnosticEventsEnabled: (request: SaveDiagnosticEventsRequest) => typedError<null, string>(__TAURI_INVOKE("save_diagnostic_events_enabled", { request })),
	saveDetailedLogsEnabled: (request: SaveDetailedLogsRequest) => typedError<null, string>(__TAURI_INVOKE("save_detailed_logs_enabled", { request })),
	saveNewRoomNotificationsEnabled: (request: SaveNewRoomNotificationsRequest) => typedError<null, string>(__TAURI_INVOKE("save_new_room_notifications_enabled", { request })),
	showNewRoomNotification: (request: ShowNewRoomNotificationRequest) => typedError<boolean, string>(__TAURI_INVOKE("show_new_room_notification", { request })),
	savePlayerName: (request: SavePlayerNameRequest) => typedError<null, string>(__TAURI_INVOKE("save_player_name", { request })),
	selectRomFile: (currentPath: string) => typedError<string | null, string>(__TAURI_INVOKE("select_rom_file", { currentPath })),
	preflightCheck: () => typedError<PreflightResponse, string>(__TAURI_INVOKE("preflight_check")),
	generateRoms: (request: GenerateRomRequest) => typedError<GenerateRomResponse, string>(__TAURI_INVOKE("generate_roms", { request })),
	ensureRoms: (request: GenerateRomRequest) => typedError<GenerateRomResponse, string>(__TAURI_INVOKE("ensure_roms", { request })),
	startMatch: (request: LaunchRequest_Deserialize) => typedError<LaunchResponse, string>(__TAURI_INVOKE("start_match", { request })),
	stopMatch: () => typedError<null, string>(__TAURI_INVOKE("stop_match")),
	sessionStatus: () => typedError<SessionStatus, string>(__TAURI_INVOKE("session_status")),
	loadMatchHistory: () => typedError<MatchHistoryRecord[], string>(__TAURI_INVOKE("load_match_history")),
	saveMatchHistory: (matches: MatchHistoryRecord[]) => typedError<null, string>(__TAURI_INVOKE("save_match_history", { matches })),
	openLogDir: (path: string) => typedError<null, string>(__TAURI_INVOKE("open_log_dir", { path })),
	createLogArchive: (logDir: string) => typedError<LogArchiveResponse, string>(__TAURI_INVOKE("create_log_archive", { logDir })),
	uploadLogArchive: (request: UploadLogArchiveRequest) => typedError<UploadLogArchiveResponse, string>(__TAURI_INVOKE("upload_log_archive", { request })),
	openMelonds: () => typedError<number, string>(__TAURI_INVOKE("open_melonds")),
	openMelondsInputConfig: () => typedError<number, string>(__TAURI_INVOKE("open_melonds_input_config")),
	getStartupEnabled: () => typedError<boolean, string>(__TAURI_INVOKE("get_startup_enabled")),
	setStartupEnabled: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_startup_enabled", { enabled })),
};

/* Types */
export type BridgeDiagnostics = {
	role: string | null,
	phase: string | null,
	signal_url: string | null,
	session: string | null,
	ice_servers: string[] | null,
	connection_state: string | null,
	gathering_state: string | null,
	ice_state: string | null,
	selected_candidate_pair: SelectedCandidatePair | null,
	stats: BridgeStats | null,
	last_error: string | null,
};

export type BridgeStats = {
	app_to_webrtc_packets: number | null,
	app_to_webrtc_bytes: number | null,
	webrtc_to_app_packets: number | null,
	webrtc_to_app_bytes: number | null,
	dropped_no_local_target: number | null,
};

export type CourseMode = "random" | "select";

export type Defaults = {
	signal_url: string,
	room_code: string,
	host_rom_path: string,
	client_rom_path: string,
	base_rom_path: string,
	player_name: string,
	player_profile_id: string,
	roms_prepared_once: boolean,
	input_config_opened_once: boolean,
	port: number,
	diagnostic_events_enabled: boolean,
	detailed_logs_enabled: boolean,
	new_room_notifications_enabled: boolean,
	log_archive_upload_token: string,
};

export type GameSettings = {
	course_mode: CourseMode,
	course_stages: number[],
	wins: number,
	big_stars: number,
	lives: Lives,
	match_seed: string,
	rng_seeds: string[],
	input_delay_frames: number,
	input_max_frame_lead: number,
	rollback_enabled: boolean,
};

export type GameStateMismatch = {
	instance: number | null,
	frame: number | null,
	local_hash: string | null,
	remote_hash: string | null,
	basic_matches: boolean | null,
	player_global_matches: boolean | null,
	wifi_candidate_matches: boolean | null,
	render_candidate_matches: boolean | null,
	line: string,
};

export type GenerateRomRequest = {
	source_rom: string,
};

export type GenerateRomResponse = {
	host_rom: string,
	client_rom: string,
	generated: boolean,
	rom_identity: RomIdentity,
};

export type LaunchRequest = LaunchRequest_Serialize | LaunchRequest_Deserialize;

export type LaunchRequest_Deserialize = {
	role: Role,
	signal_url: string,
	room_code: string,
	port: number,
	rom_path: string,
	settings: GameSettings,
	player_names?: MatchPlayerNames | null,
	diagnostic_events_enabled?: boolean,
	detailed_logs_enabled?: boolean,
	rom_identity?: RomIdentity | null,
};

export type LaunchRequest_Serialize = {
	role: Role,
	signal_url: string,
	room_code: string,
	port: number,
	rom_path: string,
	settings: GameSettings,
	player_names?: MatchPlayerNames | null,
	diagnostic_events_enabled: boolean,
	detailed_logs_enabled: boolean,
	rom_identity?: RomIdentity | null,
};

export type LaunchResponse = {
	log_dir: string,
	melon_pid: number,
	bridge_pid: number,
};

export type Lives = "3" | "5" | "endless";

export type LogArchiveResponse = {
	archive_path: string,
	size: number,
};

export type MatchHistoryRecord = {
	id: string,
	logDir: string,
	playerIds: MatchPlayerIds,
	playerNames: MatchPlayerNames,
	role: Role,
	roomCode: string,
	settings: GameSettings,
	stages: MvlStageResult[],
	startedAt: string,
	status: MatchHistoryStatus,
};

export type MatchHistoryStatus = "running" | "completed" | "stopped";

export type MatchPlayerIds = {
	mario: string,
	luigi: string,
};

export type MatchPlayerNames = {
	mario: string,
	luigi: string,
};

export type MvlPlayerResult = {
	stars: number,
	displayed_stars: number,
	collected_stars: number,
	lives: number,
	deaths: number,
	dead: boolean,
};

export type MvlStageResult = {
	game_index: number,
	stage: number | null,
	frame: number,
	winner: number | null,
	mario: MvlPlayerResult,
	luigi: MvlPlayerResult,
	mario_match_wins: number,
	luigi_match_wins: number,
	target_wins: number,
	resolved: boolean,
	line: string,
};

export type PreflightResponse = {
	melonds_path: string,
	bridge_path: string,
	input_script: string,
	symbols_file: string,
	bridge_smoke: string,
};

export type Role = "host" | "client";

export type RomIdentity = {
	rom_pair_id: string,
	generator_id: string,
	host_rom_sha256: string,
	client_rom_sha256: string,
};

export type SaveDetailedLogsRequest = {
	enabled: boolean,
};

export type SaveDiagnosticEventsRequest = {
	enabled: boolean,
};

export type SaveNewRoomNotificationsRequest = {
	enabled: boolean,
};

export type SavePlayerNameRequest = {
	player_name: string,
};

export type SaveRomPathsRequest = {
	base_rom_path: string,
};

export type SelectedCandidatePair = {
	route: string | null,
	local_type: string | null,
	remote_type: string | null,
	local: string | null,
	remote: string | null,
	local_address: string | null,
	remote_address: string | null,
};

export type SessionStatus = {
	active: boolean,
	log_dir: string | null,
	melon: string | null,
	bridge: string | null,
	webrtc: BridgeDiagnostics | null,
	diagnostics_error: string | null,
	game_state_mismatch: GameStateMismatch | null,
	mvl_results: MvlStageResult[],
};

export type ShowNewRoomNotificationRequest = {
	title: string,
	body: string,
};

export type UploadLogArchiveRequest = {
	log_dir: string,
	upload_url: string,
	upload_token: string,
};

export type UploadLogArchiveResponse = {
	archive_path: string,
	key: string,
	size: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

